language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev libhiredis-dev
script: 
  - sh build.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - https://idobata.io/hook/f48e8f58-29d9-414e-8336-1fadb62bfa2d


